### ISSUE TITLE
建表脚本

### ISSUE THREAD

**Issue by lys791227** [wiselyman/uaa-zuul#1]
里面没有建表脚本

**Comment by doggiejohn** [comment]
sysRole.java文件里面没有getAuthorities方法

**Comment by wiselyman** [comment]
@lys791227 通过JPA的领域模型自动生成表结构，在微服务中提倡领域驱动设计，尽量不要想数据库相关的内容。这也是为什么用JPA(Hibernete)，不用mybatis的原因。

**Comment by wiselyman** [comment]
@doggiejohn 使用了`lombok`的`@Data`注解，自动生成get、set方法
